ZPLUG_HOME=$ZDOTDIR/.zplug
ZPLUG_CACHE_DIR=$ZPLUG_HOME/.cache
ZPLUG_REPOS=$ZPLUG_HOME/repos
ZPLUG_BIN=$ZPLUG_HOME/bin
ZPLUG_LOADFILE=$ZPLUG_HOME/.loadfile
ZPLUG_ERROR_LOG=$ZPLUG_HOME/.error_log

ZSHZ_DATA=$ZDOTDIR/.z
